// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF1JaKCcSDnmiPcgOlaRB_TX2iq94uy4Y',
    appId: '1:371553734836:web:06981f9d001c763d1687e1',
    messagingSenderId: '371553734836',
    projectId: 'uasmobile-59135',
    authDomain: 'uasmobile-59135.firebaseapp.com',
    storageBucket: 'uasmobile-59135.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXInrwzs42M2PCLSb5VowwCmUq1onrBwY',
    appId: '1:371553734836:android:fd0aefd81deaadde1687e1',
    messagingSenderId: '371553734836',
    projectId: 'uasmobile-59135',
    storageBucket: 'uasmobile-59135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAipXF6c8Eif7G7_ETdGMy4r8qCIxehsU',
    appId: '1:371553734836:ios:4f05d6fb254a7fb01687e1',
    messagingSenderId: '371553734836',
    projectId: 'uasmobile-59135',
    storageBucket: 'uasmobile-59135.firebasestorage.app',
    iosBundleId: 'com.example.projectAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAipXF6c8Eif7G7_ETdGMy4r8qCIxehsU',
    appId: '1:371553734836:ios:4f05d6fb254a7fb01687e1',
    messagingSenderId: '371553734836',
    projectId: 'uasmobile-59135',
    storageBucket: 'uasmobile-59135.firebasestorage.app',
    iosBundleId: 'com.example.projectAkhir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF1JaKCcSDnmiPcgOlaRB_TX2iq94uy4Y',
    appId: '1:371553734836:web:06981f9d001c763d1687e1',
    messagingSenderId: '371553734836',
    projectId: 'uasmobile-59135',
    authDomain: 'uasmobile-59135.firebaseapp.com',
    storageBucket: 'uasmobile-59135.firebasestorage.app',
  );
}
